# Generated by Django 3.2.9 on 2021-12-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books',
        ),
    ]
