# Generated by Django 3.2.9 on 2021-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nBookapp', '0002_remove_book_student'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(blank=True, to='nBookapp.Book'),
        ),
    ]
