# Generated by Django 3.2.9 on 2021-11-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nBookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
    ]
