# Generated by Django 3.2.9 on 2021-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nBookapp', '0002_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.CharField(default='No owner', max_length=40),
        ),
    ]
