# Generated by Django 3.2.7 on 2021-11-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nBookapp', '0002_auto_20211124_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='isAnswered',
            field=models.BooleanField(default=False),
        ),
    ]
