# Generated by Django 3.2.9 on 2021-12-02 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nBookapp', '0004_carrel_owner_carrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 13, 34, 41, 264340)),
        ),
    ]
